# Generated by Django 4.0.1 on 2022-01-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default=None, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spotify_data', models.JSONField(default=dict, null=True)),
                ('custom_data', models.JSONField(default=dict, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('album_type', models.CharField(choices=[
                    ('ALBUM', 'Album'),
                    ('SINGLE', 'Single'),
                    ('COMPILATION', 'Compilation')
                ], default='ALBUM', max_length=12)),
                ('total_tracks', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default=None, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spotify_data', models.JSONField(default=dict, null=True)),
                ('custom_data', models.JSONField(default=dict, null=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default=None, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spotify_data', models.JSONField(default=dict, null=True)),
                ('custom_data', models.JSONField(default=dict, null=True)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/artists/')),
                ('artist', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='images',
                    to='catalog.artist',
                )),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='catalog.Genre'),
        ),
        migrations.CreateModel(
            name='AlbumImageResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/albums/')),
                ('album', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='images',
                    to='catalog.album',
                )),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='catalog.Artist'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(default=None, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('spotify_data', models.JSONField(default=dict, null=True)),
                ('custom_data', models.JSONField(default=dict, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('track_number', models.IntegerField()),
                ('disc_number', models.IntegerField(default=1)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField(default=False)),
                ('album', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='tracks',
                    to='catalog.album'),
                 ),
            ],
            options={
                'unique_together': {('album', 'track_number')},
            },
        ),
    ]
