"""
Django settings for juke_backend project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import sys
from pathlib import Path
from urllib.parse import urljoin

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

_supported_envs = {"development", "staging", "production"}
RUNTIME_ENV = os.environ.get("JUKE_RUNTIME_ENV", "development").strip().lower()
if RUNTIME_ENV not in _supported_envs:
    raise ValueError(f"JUKE_RUNTIME_ENV must be one of {_supported_envs}, got '{RUNTIME_ENV}'")

def _required_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise ValueError(f"{name} must be set")
    return value


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = RUNTIME_ENV == "development"

BACKEND_URL = _required_env("BACKEND_URL").rstrip('/')
FRONTEND_URL = _required_env("FRONTEND_URL")
LOGIN_REDIRECT_URL = FRONTEND_URL
LOGOUT_REDIRECT_URL = FRONTEND_URL
SOCIAL_AUTH_LOGIN_REDIRECT_URL = FRONTEND_URL

_cmd = sys.argv[1] if len(sys.argv) > 1 else ''
SPOTIFY_USE_STUB_DATA = os.environ.get("SPOTIFY_USE_STUB_DATA")
if SPOTIFY_USE_STUB_DATA is None:
    SPOTIFY_USE_STUB_DATA = _cmd == 'test'
else:
    SPOTIFY_USE_STUB_DATA = SPOTIFY_USE_STUB_DATA.lower() in {'1', 'true', 'yes', 'on'}

allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS")
if allowed_hosts:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
        "10.0.2.2",  # Android emulator loopback to host
        "web",
    ]

AUTH_USER_MODEL = "juke_auth.JukeUser"

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = int(_required_env("EMAIL_PORT"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

# Use console email backend in development to avoid SMTP auth issues
# Emails will be printed to the terminal instead of being sent
if RUNTIME_ENV == "development":
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

def _env_flag(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


DISABLE_REGISTRATION = _env_flag('DISABLE_REGISTRATION', False)

REST_REGISTRATION = {
    'REGISTER_VERIFICATION_ENABLED': not DISABLE_REGISTRATION,
    'REGISTER_EMAIL_VERIFICATION_ENABLED': not DISABLE_REGISTRATION,
    'RESET_PASSWORD_VERIFICATION_ENABLED': not DISABLE_REGISTRATION,

    'REGISTER_VERIFICATION_URL': os.environ.get('REGISTER_VERIFICATION_URL', 'https://frontend-host/verify-user/'),
    'RESET_PASSWORD_VERIFICATION_URL': os.environ.get('RESET_PASSWORD_VERIFICATION_URL', 'https://frontend-host/reset-password/'),
    'REGISTER_EMAIL_VERIFICATION_URL': os.environ.get('REGISTER_EMAIL_VERIFICATION_URL', 'https://frontend-host/verify-email/'),

    'VERIFICATION_FROM_EMAIL': os.environ.get("EMAIL_HOST_USER"),

    'REGISTER_VERIFICATION_EMAIL_TEMPLATES': {
        'subject': 'juke_auth/register/subject.txt',
        'text_body': 'juke_auth/register/body.txt',
        'html_body': 'juke_auth/register/body.html',
    }
}


# Application definition


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_registration',
    'social_django',
    'django_filters',
    'django_extensions',
    'juke_auth',
    'catalog',
    'recommender',
    'powerhour',
    'tunetrivia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.spotify.SpotifyOAuth2',

)

SOCIAL_AUTH_AUTHENTICATION_BACKENDS = (
    'social_core.backends.spotify.SpotifyOAuth2',
)

SOCIAL_AUTH_SPOTIFY_KEY = os.environ.get("SOCIAL_AUTH_SPOTIFY_KEY")
SOCIAL_AUTH_SPOTIFY_SECRET = os.environ.get("SOCIAL_AUTH_SPOTIFY_SECRET")
_spotify_scope = os.environ.get(
    "SOCIAL_AUTH_SPOTIFY_SCOPE",
    "user-read-playback-state user-read-currently-playing user-modify-playback-state",
)
SOCIAL_AUTH_SPOTIFY_SCOPE = [entry.strip() for entry in _spotify_scope.replace(",", " ").split() if entry.strip()]
SPOTIFY_REDIRECT_PATH = '/api/v1/social-auth/complete/spotify/'
SOCIAL_AUTH_SPOTIFY_REDIRECT_URI = urljoin(f"{BACKEND_URL}/", SPOTIFY_REDIRECT_PATH.lstrip('/'))
if SOCIAL_AUTH_SPOTIFY_KEY:
    os.environ["SPOTIPY_CLIENT_ID"] = SOCIAL_AUTH_SPOTIFY_KEY
if SOCIAL_AUTH_SPOTIFY_SECRET:
    os.environ["SPOTIPY_CLIENT_SECRET"] = SOCIAL_AUTH_SPOTIFY_SECRET

SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'juke_auth.pipeline.relink_social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'social_core.pipeline.social_auth.associate_by_email',
)

SOCIAL_AUTH_STRATEGY = 'juke_auth.strategy.ResilientStrategy'
SOCIAL_AUTH_STATE_CACHE_TTL = int(os.environ.get('SOCIAL_AUTH_STATE_CACHE_TTL', '600'))
SOCIAL_AUTH_STATE_CACHE_PREFIX = os.environ.get('SOCIAL_AUTH_STATE_CACHE_PREFIX', 'social-state')

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("POSTGRES_NAME"),
        'USER': os.environ.get("POSTGRES_USER"),
        'PASSWORD': os.environ.get("POSTGRES_PASSWORD"),
        'HOST': 'db',
        'PORT': _required_env("POSTGRES_PORT"),
    }
}

# Application definition
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


celery_always_eager = os.environ.get('CELERY_TASK_ALWAYS_EAGER')
if celery_always_eager is None:
    CELERY_TASK_ALWAYS_EAGER = _cmd == 'test'
else:
    CELERY_TASK_ALWAYS_EAGER = celery_always_eager.lower() in {'1', 'true', 'yes', 'on'}

CELERY_BROKER_URL = _required_env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'catalog.tasks.sync_spotify_genres': {'queue': 'catalog'},
}
CELERY_BEAT_SCHEDULE = {
    'sync-spotify-genres-daily': {
        'task': 'catalog.tasks.sync_spotify_genres',
        'schedule': 60 * 60 * 24,  # 24 hours
    },
}
# Keep Redis-queued tasks invisible long enough for workers to finish after fetching.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': int(os.environ.get('CELERY_VISIBILITY_TIMEOUT', '3600')),
}
# Rely on Redis keyspace events instead of aggressive prefetching to reduce idle CPU.
CELERY_WORKER_DISABLE_PREFETCH = True
# With prefetch disabled we still cap to one task per worker process for deterministic flow.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

RECOMMENDER_ENGINE_BASE_URL = _required_env("RECOMMENDER_ENGINE_BASE_URL")
RECOMMENDER_ENGINE_TIMEOUT = int(os.environ.get('RECOMMENDER_ENGINE_TIMEOUT', '15'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip().rstrip('/') for origin in cors_origins.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [FRONTEND_URL.rstrip('/')]

CORS_ALLOW_CREDENTIALS = True

default_csrf = [origin.rstrip('/') for origin in CORS_ALLOWED_ORIGINS]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(default_csrf))
