# Generated by Django 4.0 on 2026-01-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juke_auth', '0002_musicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='favorite_albums',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='favorite_artists',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='favorite_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='favorite_tracks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='musicprofile',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
