# Generated by Django 4.0 on 2026-01-18
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def deduplicate_music_profiles(apps, schema_editor):
    MusicProfile = apps.get_model('juke_auth', 'MusicProfile')
    duplicates = (
        MusicProfile.objects.values('user_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    for entry in duplicates:
        user_id = entry['user_id']
        profiles = list(MusicProfile.objects.filter(user_id=user_id).order_by('id'))
        for extra in profiles[1:]:
            extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('juke_auth', '0003_musicprofile_details'),
    ]

    operations = [
        migrations.RunPython(deduplicate_music_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='musicprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=models.PROTECT,
                related_name='music_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
