# Generated by Django 6.0.1 on 2026-01-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juke_auth', '0005_musicprofile_globe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofile',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
