# Generated by Django 6.0.1 on 2026-01-21 01:48

import django.db.models.deletion
import powerhour.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerHourSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                (
                    'invite_code',
                    models.CharField(
                        default=powerhour.models.generate_invite_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ('tracks_per_player', models.PositiveIntegerField(default=3)),
                ('max_tracks', models.PositiveIntegerField(default=30)),
                ('seconds_per_track', models.PositiveIntegerField(default=60)),
                (
                    'transition_clip',
                    models.CharField(
                        choices=[
                            ('airhorn', 'Air Horn'),
                            ('buzzer', 'Buzzer'),
                            ('bell', 'Bell'),
                            ('whistle', 'Whistle'),
                            ('glass_clink', 'Glass Clink'),
                        ],
                        default='airhorn',
                        max_length=50,
                    ),
                ),
                ('hide_track_owners', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('lobby', 'Lobby'),
                            ('active', 'Active'),
                            ('paused', 'Paused'),
                            ('ended', 'Ended'),
                        ],
                        default='lobby',
                        max_length=20,
                    ),
                ),
                ('current_track_index', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                (
                    'admin',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hosted_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionPlayer',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to='powerhour.powerhoursession',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SessionTrack',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('order', models.PositiveIntegerField()),
                ('start_offset_ms', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                (
                    'added_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_tracks_added',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='powerhour.powerhoursession',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.track',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'track')},
            },
        ),
    ]
