# Generated by Django 6.0.1 on 2026-01-23 05:48

import django.db.models.deletion
import tunetrivia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuneTriviaLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_correct_songs', models.IntegerField(default=0)),
                ('total_correct_artists', models.IntegerField(default=0)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tunetrivia_leaderboard',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='TuneTriviaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=tunetrivia.models.generate_session_code, max_length=6, unique=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[('host', 'Host Mode'), ('party', 'Party Mode')],
                        default='party',
                        max_length=10,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('lobby', 'Lobby'),
                            ('playing', 'Playing'),
                            ('paused', 'Paused'),
                            ('finished', 'Finished'),
                        ],
                        default='lobby',
                        max_length=10,
                    ),
                ),
                ('max_songs', models.PositiveIntegerField(default=10)),
                ('seconds_per_song', models.PositiveIntegerField(default=30)),
                ('enable_trivia', models.BooleanField(default=True)),
                ('auto_select_decade', models.CharField(blank=True, max_length=20, null=True)),
                ('auto_select_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_select_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                (
                    'host',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hosted_tunetrivia_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuneTriviaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('playing', 'Playing'),
                            ('revealed', 'Revealed'),
                            ('finished', 'Finished'),
                        ],
                        default='pending',
                        max_length=10,
                    ),
                ),
                ('spotify_track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=300)),
                ('artist_name', models.CharField(max_length=300)),
                ('album_name', models.CharField(blank=True, max_length=300)),
                ('album_art_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('trivia', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rounds',
                        to='tunetrivia.tunetriviasession',
                    ),
                ),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('session', 'round_number'), ('session', 'spotify_track_id')},
            },
        ),
        migrations.CreateModel(
            name='TuneTriviaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('is_host', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tunetrivia_participations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to='tunetrivia.tunetriviasession',
                    ),
                ),
            ],
            options={
                'ordering': ['-total_score', 'joined_at'],
                'unique_together': {('session', 'display_name'), ('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TuneTriviaGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_guess', models.CharField(blank=True, max_length=300, null=True)),
                ('artist_guess', models.CharField(blank=True, max_length=300, null=True)),
                ('song_correct', models.BooleanField(default=False)),
                ('artist_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='guesses',
                        to='tunetrivia.tunetriviaplayer',
                    ),
                ),
                (
                    'round',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='guesses',
                        to='tunetrivia.tunetriviaround',
                    ),
                ),
            ],
            options={
                'unique_together': {('round', 'player')},
            },
        ),
    ]
