# Generated by Django 4.0 on 2026-01-18
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=32)),
                ('quality_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'artist',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='catalog.artist',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrackEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=32)),
                ('quality_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'track',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='catalog.track',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AlbumEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=32)),
                ('quality_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'album',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embedding',
                        to='catalog.album',
                    ),
                ),
            ],
        ),
    ]
