# Generated by Django 6.0.1 on 2026-01-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('key', models.IntegerField()),
                ('mode', models.CharField(max_length=5)),
                ('danceability', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                (
                    'track',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audio_features',
                        to='catalog.track',
                    ),
                ),
            ],
        ),
    ]
